#!/usr/bin/env bash
# A Bash script that prints a message forever and handles SIGTERM by saying "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
