#!/usr/bin/env bash
# A Bash script that prints a message forever and handles SIGTERM by saying "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

# A Bash script that stops the 4-to_infinity_and_beyond process without using kill or killall
pkill -f 7-highlander
